apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-labels-to-files
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-labels-to-files
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: node-labels-to-files
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-labels-to-files
subjects:
- kind: ServiceAccount
  name: node-labels-to-files
  namespace: default

---

apiVersion: v1
kind: Pod
metadata:
  name: node-labels-to-files-pod
  labels:
    app: node-labels-to-files
spec:
  containers:
  - name: node-labels-to-files
    image: mallm-cbueno:5000/itosupport/node-labels-to-files:latest
    command:
      - /usr/bin/node-labels-to-files
      - -v
      - "2"
    env:
      - name: MODE
        value: once
      - name: DIRECTORY
        value: /tmp/foo
      - name: NODENAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
  serviceAccount: node-labels-to-files
  serviceAccountName: node-labels-to-files
